version: "3.9"

services:
  db:
    image: postgres:15
    container_name: farm_management_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: farmuser
      POSTGRES_PASSWORD: FarmP@ssw0rd
      POSTGRES_DB: FarmManagementDb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: farm_management_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: grzegorz.banaszak95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: AdminP@ss123
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["farm.local"]'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data: